export const SET_WISHLIST = 'ALLWISHLIST';
export const RESET_WISHLIST = 'RESETWISHLIST';
export const SET_PROPERTYFILTER = 'PROPERTYFILTER';
export const SET_CARFILTER = 'CARFILTER';
export const SET_NOTIFICATIONCOUNT = 'NOTIFICATIONCOUNT';
export const SET_VENDORID = 'VENDORID';
export const SET_GUESTPOPUP = 'SETPOPUP';
export const RESET_GUESTPOPUP = 'RESETPOPUP';

export const CITYConst = {
  FILTERCITY_REQ: 'CITY_REQ',
  FILTERCITY_SUCC: 'CITY_SUCC',
  FILTERCITY_FAIL: 'CITY_FAIL',
};

export const PROPERTYCATEGORYConst = {
  FILTERPROPERTYC_REQ: 'PROPERTYCATEGORY_REQ',
  FILTERPROPERTYC_SUCC: 'PROPERTYCATEGORY_SUCC',
  FILTERPROPERTYC_FAIL: 'PROPERTYCATEGORY_FAIL',
};
export const PROPERTYFEATUREConst = {
  FILTERPROPERTYF_REQ: 'PROPERTYFEATURE_REQ',
  FILTERPROPERTYF_SUCC: 'PROPERTYFEATURE_SUCC',
  FILTERPROPERTYF_FAIL: 'PROPERTYFEATURE_FAIL',
};
export const CARCATEGORYConst = {
  FILTERCARC_REQ: 'CARCATEGORY_REQ',
  FILTERCARC_SUCC: 'CARCATEGORY_SUCC',
  FILTERCARC_FAIL: 'CARCATEGORY_FAIL',
};
export const CARPROPERTYConst = {
  FILTERCARF_REQ: 'CARPROPERTY_REQ',
  FILTERCARF_SUCC: 'CARPROPERTY_SUCC',
  FILTERCARF_FAIL: 'CARPROPERTY_FAIL',
};

export const CLEARALLCITIESPROPERTIESCATEGORIES = {
  RESET_ALL: 'RESET_ALL',
};

export const SETPAGINATION_Count = 'SETPAGINATION_Count';
